### ISSUE TITLE
sudo docker build -t isaac_sdk . failed on Jetson Nano

### ISSUE THREAD

**Issue by Avi-avidan** [atinfinity/isaac_sdk_docker#2]
any advice would be very appreciated. thanks.

here is my log

Sending build context to Docker daemon  7.621GB
Step 1/16 : FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
10.0-cudnn7-devel-ubuntu18.04: Pulling from nvidia/cuda
7ddbc47eeb70: Pull complete
c1bbdc448b72: Pull complete
8c3b70e39044: Pull complete
45d437916d57: Pull complete
d8f1569ddae6: Pull complete
de5a2c57c41d: Pull complete
ea6f04a00543: Pull complete
7b872974e97c: Pull complete
ba8a751eb7d9: Pull complete
c23d51d23979: Pull complete
Digest: sha256:e277b9eef79d6995b10d07e30228daa9e7d42f49bcfc29d512c1534b42d91841
Status: Downloaded newer image for nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
 ---> a387f44414ed
Step 2/16 : ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
 ---> Running in 1187e10caaf0
Removing intermediate container 1187e10caaf0
 ---> 8994173095d2
Step 3/16 : ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics
 ---> Running in 8ee291689c5e
Removing intermediate container 8ee291689c5e
 ---> a0f54f984a4c
Step 4/16 : ENV USERNAME isaac
 ---> Running in de0e0d860fc2
Removing intermediate container de0e0d860fc2
 ---> 8e4700ffe6fc
Step 5/16 : ENV HOME /home/$USERNAME
 ---> Running in 9dfba64036b4
Removing intermediate container 9dfba64036b4
 ---> e64f53d39efb
Step 6/16 : RUN useradd -m $USERNAME &&         echo "$USERNAME:$USERNAME" | chpasswd &&         usermod --shell /bin/bash $USERNAME &&         usermod -aG sudo $USERNAME &&         mkdir /etc/sudoers.d &&         echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME &&         chmod 0440 /etc/sudoers.d/$USERNAME &&         usermod  --uid 1000 $USERNAME &&         groupmod --gid 1000 $USERNAME
 ---> Running in 39675d07c971
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c useradd -m $USERNAME &&         echo "$USERNAME:$USERNAME" | chpasswd &&         usermod --shell /bin/bash $USERNAME &&         usermod -aG sudo $USERNAME &&         mkdir /etc/sudoers.d &&         echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME &&         chmod 0440 /etc/sudoers.d/$USERNAME &&         usermod  --uid 1000 $USERNAME &&         groupmod --gid 1000 $USERNAME' returned a non-zero code: 1

**Comment by atinfinity** [comment]
@Avi-avidan Could you please give me the following information?

## Hardware
- CPU: x86_64? aarch64?

## Software
- Docker version
- NVIDIA Isaac SDK version

**Comment by Avi-avidan** [comment]
quad-core ARM A57 64-bit CPU ([full spec here]
(https://developer.nvidia.com/embedded/jetson-nano-developer-kit))
Ubuntu 18.04 aarch64
Docker version 19.03.6, build 369ce74a3c
isaac-sdk-20191213-65ec14db.tar.xz

**Comment by atinfinity** [comment]
@Avi-avidan I supposed that this Dockerfile is used on `x86_64` architecture.
Because, `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04` image supports only this architecture.

And, please read this document.
https://docs.nvidia.com/isaac/isaac/doc/tutorials/nano.html

I think that you should build applications on `x86_64` and deploy to Jetson device.

**Comment by Avi-avidan** [comment]
thanks. this is very helpful.
