### ISSUE TITLE
stop at install_dependencies.sh

### ISSUE THREAD

**Issue by mynameisken** [atinfinity/isaac_sdk_docker#4]
Step 17/21 : COPY install_dependencies.sh /home/$USERNAME/isaac_sdk/engine/build/scripts/
 ---> 9a459a4d1d20
Step 18/21 : RUN  cd isaac_sdk &&     bash engine/build/scripts/install_dependencies.sh &&     mkdir -p /home/$USERNAME/isaac_sim_unity3d && USER root
 ---> Running in ea053aa261cc
Get:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease [265 kB]
Get:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease [111 kB]
Get:3 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports InRelease [98.3 kB]
Get:5 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease [107 kB]
Get:6 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/multiverse Sources [208 kB]
Get:7 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/restricted Sources [7198 B]
Get:8 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/universe Sources [12.3 MB]
Get:4 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease [23.2 kB]
Get:10 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/main Sources [1079 kB]
Get:9 https://packagecloud.io/github/git-lfs/ubuntu bionic/main amd64 Packages [3505 B]
Get:12 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/main amd64 Packages [1275 kB]
Get:13 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
Get:14 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:15 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/restricted amd64 c-n-f Metadata [392 B]
Get:16 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/universe amd64 Packages [11.3 MB]
Ign:11 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:17 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:20 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]
Get:21 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:22 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]
Get:23 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main Sources [220 kB]
Get:24 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/universe Sources [66.0 kB]
Get:25 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/multiverse Sources [4945 B]
Get:26 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/restricted Sources [4541 B]
Get:27 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 Packages [423 kB]
Get:28 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/main amd64 c-n-f Metadata [8516 B]
Get:29 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/restricted amd64 Packages [39.3 kB]
Get:30 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/restricted amd64 c-n-f Metadata [324 B]
Get:31 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/universe amd64 Packages [198 kB]
Get:32 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/universe amd64 c-n-f Metadata [5276 B]
Get:33 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/multiverse amd64 Packages [17.3 kB]
Get:34 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [480 B]
Get:35 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/universe Sources [1664 B]
Get:36 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/main amd64 c-n-f Metadata [112 B]
Get:37 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]
Get:38 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/universe amd64 Packages [3216 B]
Get:39 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/universe amd64 c-n-f Metadata [224 B]
Get:40 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
Get:41 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main Sources [58.6 kB]
Get:42 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse Sources [638 B]
Get:43 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted Sources [4545 B]
Get:44 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe Sources [8515 B]
Get:45 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main amd64 Packages [204 kB]
Get:46 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main amd64 c-n-f Metadata [4220 B]
Get:47 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted amd64 Packages [39.1 kB]
Get:48 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted amd64 c-n-f Metadata [324 B]
Get:49 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe amd64 Packages [65.1 kB]
Get:50 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe amd64 c-n-f Metadata [2180 B]
Get:51 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse amd64 Packages [1078 B]
Get:52 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse amd64 c-n-f Metadata [116 B]
Get:18 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:19 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:53 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:54 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Ign:55 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
Ign:55 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:56 https://developer.download.nvidia.cn/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [43.7 kB]
Ign:55 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
Err:55 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64  Packages
  404  Not Found [IP: 60.167.130.134 443]
Traceback (most recent call last):
  File "/usr/lib/cnf-update-db", line 26, in <module>
    col.create(db)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 93, in create
    self._fill_commands(con)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 127, in _fill_commands
    self._parse_single_commands_file(con, fp)
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 165, in _parse_single_commands_file
    suite=tagf.section["suite"]
KeyError: 'suite'
Fetched 28.8 MB in 27s (1080 kB/s)
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu1804/x86_64/by-hash/SHA256/aae84903f5252806fa9df09e843131693f34cdcec37eb957458a0fd3c25f94d7  404  Not Found [IP: 60.167.130.134 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
E: Sub-process returned an error code
[INFO] Installing packages - lsb-core
[INFO] Successfully installed packages - lsb-core
[INFO] Installing packages - git git-lfs git-review build-essential g++ redis-server
[INFO] Successfully installed packages - git git-lfs git-review build-essential g++ redis-server
Git LFS initialized.
[INFO] Installing packages - pkg-config zip zlib1g-dev unzip curl
[INFO] Successfully installed packages - pkg-config zip zlib1g-dev unzip curl
[INFO] Installing packages - uuid-dev
[INFO] Successfully installed packages - uuid-dev
[INFO] Installing packages - python python-dev
[INFO] Successfully installed packages - python python-dev
[INFO] Installing packages - libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
[INFO] Successfully installed packages - libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
[INFO] Installing packages - sox
[INFO] Successfully installed packages - sox
[INFO] Installing packages - gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
[INFO] Successfully installed packages - gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
[INFO] Installing packages - libvpx5 libtwolame-dev libtheora-bin libspeex1
E: Unable to locate package libvpx5
[ERROR] Failed to install packages - libvpx5 libtwolame-dev libtheora-bin libspeex1
The command '/bin/sh -c cd isaac_sdk &&     bash engine/build/scripts/install_dependencies.sh &&     mkdir -p /home/$USERNAME/isaac_sim_unity3d && USER root' returned a non-zero code: 1
PS D:\isaac\isaac_sdk_docker-master>

always get the same error, can you give me a clue? :)

**Comment by atinfinity** [comment]
@mynameisken Could you please report the following information?

- Platform of Host Machine
- Docker version
- NVIDIA Isaac SDK version

> PS D:\isaac\isaac_sdk_docker-master>

I guessed that the platform of your  host machine is Windows.  
But, I tested only Ubuntu.

**Comment by mynameisken** [comment]
Thanks a lot for your reply!

I tested it on windows10 host.
The docker version is Docker desktop 2.3.0.4
And the ISAAC SDK version is “isaac-sdk-20200527-0159e2bab.tar.xz”.

I guess that my host is inside of the “China Wall”, so some connetions are unreachable. But I do not have any good idea to solve it.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: atinfinity<mailto:notifications@github.com>
发送时间: 2020年8月25日 13:13
收件人: atinfinity/isaac_sdk_docker<mailto:isaac_sdk_docker@noreply.github.com>
抄送: Ken - 高剑<mailto:cn_gj@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [atinfinity/isaac_sdk_docker] stop at install_dependencies.sh (#4)


@mynameisken<https://github.com/mynameisken> Could you please report the following information?

  *   Platform of Host Machine
  *   Docker version
  *   NVIDIA Isaac SDK version

PS D:\isaac\isaac_sdk_docker-master>

I think that the platform of your host machine is Windows.
But, I tested only Ubuntu.

―

**Comment by atinfinity** [comment]
@mynameisken My Dockerfile used `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04` as base image.

> Step 18/21 : RUN cd isaac_sdk && bash engine/build/scripts/install_dependencies.sh && mkdir -p /home/$USERNAME/isaac_sim_unity3d && USER root
> ---> Running in ea053aa261cc
> Get:1 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal InRelease [265 kB]
> Get:2 https://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-updates InRelease [111 kB]

But, your log includes `focal`(=Ubuntu 20.04) message.  
I could not understand the reason.

**Comment by atinfinity** [comment]
@mynameisken If you does not addtional information, I'll close this issue.

**Comment by atinfinity** [comment]
I closed this issue.
